name: Wheels
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish wheels'
        required: true
        default: false
        type: boolean

jobs:
  Build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Override toolchain
      if: ${{ matrix.os }} == 'windows-latest'
      run: rustup set default-host x86_64-pc-windows-gnu

    - name: Build wheels
      uses: pypa/cibuildwheel@v3.0.0

    - name: Upload artifacts
      if: (github.ref == 'refs/heads/master') && inputs.publish
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl
